### ISSUE TITLE
🚀 Feature Request: Add open-collective donate button

### ISSUE THREAD

**Issue by ishaaa-ai** [grey-software/LinkedIn-Focus#35]
### Problem Overview 👁️‍🗨️ 

Users should be able to see the open-collective donate button along with the PayPal and GitHub Sponsors button, when they use the LinkedIn-Focus extension.

### What would you like? 🧰

We would like to have the an exact replica of the PayPal button except the PayPal logo should be replaced with the open-collective logo (image can be found below).

Use #87ADEC for the color of the button.

![image](https://user-images.githubusercontent.com/56453971/96580311-1a4c2100-12a6-11eb-81ee-20610da07355.png)

### What alternatives have you considered? 🔍

N/A

### Additional details ℹ️

To look at a similar implementation check out https://github.com/grey-software/LinkedIn-Focus/pull/27.

**Comment by varunpappu** [comment]
@ishaaa-ai  Hey can you assign this to me.. I would like to work on it.
