### ISSUE TITLE
🚀 Feature Request: Add Grey Software sticker & Project logo

### ISSUE THREAD

**Issue by ishaaa-ai** [grey-software/LinkedIn-Focus#38]
### Problem Overview 👁️‍🗨️ 

Users should be able to see the Grey Software sticker and the LinkedIn-Focus logo on the README.md file.

### What would you like? 🧰

We want the Grey Software sticker and the LinkedIn-Focus logo as the header on the README.md file. Below is an example. You would also need to add the Grey Software sticker next to it.

![image](https://user-images.githubusercontent.com/56453971/96623913-0ae6cb00-12da-11eb-818c-4aca659da710.png)

### What alternatives have you considered? 🔍

N/A

### Additional details ℹ️

The Linked-In Focus logo image can be found in this repository under the **src** folder. The file name is **icon.png**. Below is the image of the Grey Software sticker that should be used.

![image](https://user-images.githubusercontent.com/56453971/96623859-f99dbe80-12d9-11eb-8500-bded5bfc7469.png)

**Comment by Owen000** [comment]
Can you assign me?
