### ISSUE TITLE
🚀 Feature Request: Update extension logo and title color

### ISSUE THREAD

**Issue by ishaaa-ai** [grey-software/LinkedIn-Focus#42]
### Problem Overview 👁️‍🗨️ 

LinkedIn changed their default color to #0073b1. We want to update this color on our codebase as well.

### What would you like? 🧰

We want to update our the color to #0073b1 at the places indicated by the arrows in the image below.

![image](https://user-images.githubusercontent.com/56453971/97149783-9a113a00-1743-11eb-940d-49a646abb32f.png)

### What alternatives have you considered? 🔍

N/A

### Additional details ℹ️

The logo.png file can be found under the **src** directory. You will need to update this logo image using the color specified above. To update the title color and the LinkedIn button (as indicated in the image above), you will need to modify the color used for these in the **focus.js** file (can be found in the **src** directory).

**Comment by isabellaliu77** [comment]
Hi, can you assign me this issue? Thanks.

**Comment by anubhavcodes** [comment]
@aseidma Are you still working on this issue? I can take it up if you are no longer working on it. :)

**Comment by aseidma** [comment]
@anubhavcodes Just pushed the PR an hour ago. :) #43
